version: '3.6'

services:
  mongodb:
    image: mongo:latest
    container_name: garden-planner-mongodb
    environment:
      - MONGODB_DATABASE="gardening-planner"
    ports:
      - 27017:27017
    restart: unless-stopped
