version: '3.8'

services:
  node:
    image: hortus-api:latest
    container_name: hortus-node-api
    build:
      context: .
      target: ${NODE_ENV} # Change this to prod
      dockerfile: ./Dockerfile
    #command: npm run start:dev # Change this to prod
    ports:
      - 3333:${API_PORT}
    networks:
      - hortus
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - database
      - cache
      - session
  database:
    image: mongo:4.4.8 # < 5 for AVX CPU support
    container_name: hortus-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=development
      - MONGO_INITDB_USER=mongodb
      - MONGO_INITDB_PWD=mongodb
      - MONGODB_SYSTEM_LOG_VERBOSITY=3
    ports:
      - 27017:${DATABASE_PORT}
    restart: always
  cache:
    image: redis:latest
    container_name: hortus-cache
    command: --port ${CACHE_PORT}
    ports:
      - ${CACHE_PORT}:${CACHE_PORT}
    restart: always
  session:
    image: redis:latest
    container_name: hortus-session
    command: --port ${SESSION_PORT}
    ports:
      - ${SESSION_PORT}:${SESSION_PORT}
    restart: always

networks:
  hortus:

volumes:
  cache:
  database:
  media:
