version: '3.8'

services:
  api:
    image: hortus-api:latest
    container_name: hortus-api
    build:
      context: .
      target: ${NODE_ENV}
      dockerfile: ./Dockerfile
    command: npm run start:${NODE_ENV}
    ports:
      - 3333:${API_PORT}
    networks:
      - hortus
    volumes:
      - .:/usr/src/app
      - media_data:/upload
    restart: unless-stopped
    depends_on:
      - database
      - cache
      - session
  static:
    image: nginx:latest
    container_name: hortus-static-server
    ports:
      - '8000:8080'
    networks:
      - hortus
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - media_data:/usr/share/nginx/html # nginx default
  database:
    image: mongo:4.4.8 # < 5 for AVX CPU support
    container_name: hortus-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
      - MONGO_INITDB_USER=${DATABASE_USERNAME}
      - MONGO_INITDB_PWD=${DATABASE_PASSWORD}
      - MONGODB_SYSTEM_LOG_VERBOSITY=3
    command: --auth
    ports:
      - 27017:${DATABASE_PORT}
    volumes:
      - database_data:/data/db
      - database_config:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    restart: always
  cache:
    image: redis:latest
    container_name: hortus-cache
    command: --port ${CACHE_PORT}
    ports:
      - ${CACHE_PORT}:${CACHE_PORT}
    volumes:
      - cache_data:/data
    restart: always
  session:
    image: redis:latest
    container_name: hortus-session
    command: --port ${SESSION_PORT}
    ports:
      - ${SESSION_PORT}:${SESSION_PORT}
    volumes:
      - session_data:/data
    restart: always
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@database:27017/${DATABASE_NAME}
    depends_on:
      - database

networks:
  hortus:

volumes:
  cache_data:
  session_data:
  database_data:
  database_config:
  media_data:
