version: '3.8'

services:
  node:
    container_name: hortus-node-api
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3333:3333
    networks:
      - hortus-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:latest
    container_name: hortus-mongo-database
    environment:
      - MONGODB_DATABASE="gardening-planner"
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongo/data:/data/db # Helps to store MongoDB data in `./mongo/data`, to be removed, backup volume ?
  redis:
    image: redis:latest
    container_name: hortus-redis-session
    ports:
      - 6379:6379

networks:
  hortus-network:

volumes:
  redisdata:
  mongodata:
  mediadata:
